In [2]:
import pandas as pd

In [27]:
Math_df = pd.read_json("MATH_error_analysis_1.jsonl", lines=True)
GSM8K_df = pd.read_json("GSM8Kgsm8k_error_analysis.jsonl", lines=True)

Math_df
# GSM8K_df

,question_id,category,question,reasoning_steps,model_answer,level,gt_solution,correct_answer,is_correct,total_log_prob,stepwise_log_probs,Analysis,Erroneous steps
0,1,counting_and_probability,$n$ fair 6-sided dice are simultaneously rolle...,Step 1: Let's define the problem in terms of p...,Answer not found,4,"For $n$ dice, there are $\binom{n}{2}=\frac{n(...",4.0,False,-93.624027,"{'Step 1:': -0.24121332510000001, 'Step 2:': -...",Erroneous steps: \n- Step 6\n- Step 9\nExplana...,Erroneous steps: \n- Step 6\n- Step 9\n
1,2,counting_and_probability,When rolling a certain unfair six-sided die wi...,Step 1: Let's denote the probability of obtain...,289.0,5,"Let $p(a,b)$ denote the probability of obtaini...",29.0,False,-128.082638,"{'Step 1:': -0.1453271709, 'Step 2:': -0.15383...",Erroneous steps: \n- Step 9: The calculation o...,Erroneous steps: \n- Step 9: The calculation o...
2,3,counting_and_probability,When rolling a certain unfair six-sided die wi...,Step 1: Let's denote the probability of obtain...,17.0,5,"Let $p(a,b)$ denote the probability of obtaini...",29.0,False,-181.785633,"{'Step 1:': -0.2135267627, 'Step 2:': -0.15305...",Erroneous steps:\n \n**Step 18**: The error b...,Erroneous steps:\n \n**Step 18**: The error b...
3,4,counting_and_probability,"In how many ways can one write the numbers 1, ...",Step 1: We need to consider the divisors of ea...,16.0,5,We begin by finding all possible ways to arran...,25.0,False,-112.768653,"{'Step 1:': -0.2724122194, 'Step 2:': -0.20772...","Erroneous steps: Step 8, Step 9, Step 11\n\nEx...","Erroneous steps: Step 8, Step 9, Step 11\n\n"
4,5,counting_and_probability,For how many three-element sets (order doesn't...,"Step 1: First, we need to find the prime facto...",6.0,5,The prime factorization of $2310$ is $2310 = 2...,40.0,False,-98.292079,"{'Step 1:': -0.2124449898, 'Step 2:': -0.16106...",Erroneous steps:\nExplanation: The error occur...,Erroneous steps:\n
...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,156,number_theory,There are two cameras that take pictures of a ...,Step 1: Determine the times when Camera A take...,38.0,5,If Camera A and Camera B take a picture at the...,41.0,False,-164.131489,"{'Step 1:': -0.2032439205, 'Step 2:': -0.13203...",Erroneous steps:\n\n**Step 7: Determine the fi...,Erroneous steps:\n\n**Step 7: Determine the fi...
99,157,number_theory,The number of toy cars that Ray has is a multi...,Step 1: Let the number of toy cars Ray initial...,2.0,4,Let $n=2m$. Let $b$ be the number of cars that...,3.0,False,-44.731027,"{'Step 1:': -0.143383556, 'Step 2:': -0.129873...","Erroneous steps: Step 4, specifically cases wh...","Erroneous steps: Step 4, specifically cases wh..."
100,158,number_theory,All of the even numbers from 2 to 98 inclusive...,Step 1: Consider the even numbers from 2 to 98...,4.0,4,"If the numbers 2, 4, 6, and 8 are multiplied, ...",6.0,False,-144.732229,"{'Step 1:': -0.2176476098, 'Step 2:': -0.23059...",Erroneous steps: Step 12\n\nExplanation: The e...,Erroneous steps: Step 12\n\n
101,159,number_theory,Nine different two-digit numbers can be formed...,Step 1: Identify all possible two-digit number...,6.0,2,The two-digit numbers that can be formed are 1...,7.0,False,-36.468369,"{'Step 1:': -0.2290795421, 'Step 2:': -0.09694...",Erroneous steps: Step 1\n\nExplanation: The er...,Erroneous steps: Step 1\n\n
102,160,number_theory,"A textbook has 1,000 pages. How many of the p...",Step 1: We need to find the page numbers betwe...,18.0,5,"There are only a few ways to make one, two, an...",15.0,False,-67.825493,"{'Step 1:': -0.2787903514, 'Step 2:': -0.27292...",Erroneous steps: Step 2\n\nExplanation: In Ste...,Erroneous steps: Step 2\n\n

In [98]:
# List of desired columns
Math_columns_to_keep = [
    "question_id", "category", "question", "reasoning_steps", "model_answer",
    "level", "gt_solution", "correct_answer", "is_correct",
    "total_log_prob", "stepwise_log_probs"
]

# List of row indices you want to keep
MATH_ids = [8, 10, 11, 18, 28, 29, 34, 38, 46, 57, 58] # 67

# Subset the DataFrame
Math_selected_df = Math_df[Math_df["question_id"].isin(MATH_ids)][Math_columns_to_keep]
Math_selected_df["paragraph_reasoning"] = ""
# Math_selected_df.to_json("Math_selected_incorrect_questions.jsonl", orient="records", lines=True)

Math_selected_df

,question_id,category,question,reasoning_steps,model_answer,level,gt_solution,correct_answer,is_correct,total_log_prob,stepwise_log_probs,paragraph_reasoning
7,8,counting_and_probability,The increasing list of five different integers...,Step 1: We need to find increasing lists of fi...,10.0,4,"After some trial and error, we obtain the two ...",2.0,False,-89.047330,"{'Step 1:': -0.14934915040000002, 'Step 2:': -...",
9,10,counting_and_probability,"How many numbers are in the list $$ 6,7,10,11,...",Step 1: Observe the pattern in the sequence: t...,46.0,3,We first count the even terms of the sequence....,47.0,False,-57.239853,"{'Step 1:': -0.33314112220000003, 'Step 2:': -...",
10,11,counting_and_probability,"A street has 50 houses on each side, for a tot...",Step 1: Determine the sequence of house number...,246.0,4,If we combine the house numbers on the north a...,245.0,False,-70.004683,"{'Step 1:': -0.1912033286, 'Step 2:': -0.15656...",
14,18,counting_and_probability,"The letters $A, B$ and $C$ are used to form ev...",Step 1: We need to determine the position of t...,14.0,2,There are 9 possible words that start with A t...,11.0,False,-63.576446,"{'Step 1:': -0.20251417100000002, 'Step 2:': -...",
19,28,counting_and_probability,When a fair six-sided die is tossed on a table...,Step 1: A fair six-sided die has faces numbere...,0.8333,3,"If 6 is one of the visible faces, the product ...",1.0,False,-96.622040,"{'Step 1:': -0.2463127193, 'Step 2:': -0.17836...",
20,29,counting_and_probability,Kim has $10$ identical lamps and $3$ identical...,Step 1: We need to distribute 10 identical lam...,66.0,5,Only the number of lamps on each table matters...,14.0,False,-30.274828,"{'Step 1:': -0.21624543840000002, 'Step 2:': -...",
23,34,counting_and_probability,On the student government ballot at Dusable Hi...,Step 1: Determine the number of ways to list t...,1244160.0,4,"Since there are six candidates for president, ...",12441600.0,False,-34.407995,"{'Step 1:': -0.2679094725, 'Step 2:': -0.19253...",
26,38,counting_and_probability,A $4\times 4\times 4$ open cubical box contain...,Step 1: Consider the structure of the $4 \time...,64.0,4,We count the complement. A cube that does not ...,52.0,False,-99.537313,"{'Step 1:': -0.3682932598, 'Step 2:': -0.33891...",
31,46,counting_and_probability,How many numbers can be expressed as the sum o...,"Step 1: The set given is \(\{0, 1, 2, 4, 8, 16...",29.0,5,"We see that the given numbers, expressed in bi...",31.0,False,-103.442798,"{'Step 1:': -0.1935318285, 'Step 2:': -0.28084...",
41,57,counting_and_probability,How many of the natural numbers from $1$ to $8...,Step 1: We need to find the number of natural ...,28.0,4,There are $10$ numbers with a $6$ in the hundr...,26.0,False,-71.215213,"{'Step 1:': -0.2251759852, 'Step 2:': -0.26338...",
42,58,counting_and_probability,Each digit in the number 2001 is placed on a d...,Step 1: The number 2001 consists of the digits...,1.0,2,"There are four cards total, two of which have ...",0.0,False,-71.435032,"{'Step 1:': -0.0710904223, 'Step 2:': -0.17621...",

In [143]:
Math_selected_df["reasoning_steps"][42]
Math_selected_df["paragraph_reasoning"][42] = "The number 2001 consists of the digits 2, 0, 0, and 1. We need to select three different cards such that the product of the numbers on those cards is not zero. This means we cannot select both of the '0' cards, as their product with any other digit would be zero. Let's consider the possible selections: we can select the cards with digits 2, 0, and 1; we can select the cards with digits 2, 0, and 0; and we can select the cards with digits 0, 0, and 1. Among these, only the selection of cards with digits 2, 0, and 1 results in a non-zero product, as the other selections include both '0' cards. Therefore, we need to count the number of ways to select three cards such that the product is not zero. We have only one valid selection: the cards with digits 2, 0, and 1. The number of ways to select these three cards is 1."

C:\Users\li290\AppData\Local\Temp\ipykernel_21460\2374343124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Math_selected_df["paragraph_reasoning"][42] = "The number 2001 consists of the digits 2, 0, 0, and 1. We need to select three different cards such that the product of the numbers on those cards is not zero. This means we cannot select both of the '0' cards, as their product with any other digit would be zero. Let's consider the possible selections: we can select the cards with digits 2, 0, and 1; we can select the cards with digits 2, 0, and 0; and we can select the cards with digits 0, 0, and 1. Among these, only the selection of cards with digits 2, 0, and 1 results in a non-zero product, as the other selections include both '0' cards. Therefore, we need to count the number of ways to select three cards such that the product is not zero. We have only one valid selection: the cards with digits 2, 0, and 1. The number of ways to select these three cards is 1."

In [145]:
Math_selected_df
Math_selected_df.to_json("Math_selected_incorrect_questions.jsonl", orient="records", lines=True)

In [147]:
gsm_indices = [0, 2, 4, 6, 7, 14, 16, 19, 21, 22]

# List of desired columns
columns_to_keep = [
    "question", "reasoning_steps", "model_answer", "gt_solution",
    "correct_answer", "is_correct", "total_log_prob", "stepwise_log_probs"
]

# Subset the DataFrame
gsm_selected_df = GSM8K_df.loc[gsm_indices, columns_to_keep]
# gsm_selected_df.to_json("GSM8K_selected_incorrect_questions.jsonl", orient="records", lines=True)
gsm_selected_df["paragraph_reasoning"] = ""
gsm_selected_df

,question,reasoning_steps,model_answer,gt_solution,correct_answer,is_correct,total_log_prob,stepwise_log_probs,paragraph_reasoning
0,Carla is downloading a 200 GB file. Normally s...,"Step 1: First, we need to determine how much o...",120.0,First find how many gigabytes are in 40% of th...,160,False,-44.422417,"{'Step 1:': -0.2185396467, 'Step 2:': -0.21152...",
2,John plans to sell all his toys and use the mo...,Step 1: Calculate the total amount of money Jo...,0.0,He spent $160 on video games because 8 x 20 = ...,2,False,-29.595732,"{'Step 1:': -0.1743409722, 'Step 2:': -0.13850...",
4,Luke is spending time at the beach building sa...,Step 1: The top level of the sandcastle has a ...,7.5,Level 3 is 32 square feet because 16 x 2 = <<1...,60,False,-15.143888,"{'Step 1:': -0.0866175044, 'Step 2:': -0.09407...",
6,Christina is planning a birthday party and nee...,"Step 1: First, we need to determine how many g...",18.0,She needs 12 gift bags because 16 x .75 = <<16...,24,False,-26.217186,"{'Step 1:': -0.2306994265, 'Step 2:': -0.18537...",
7,John likes to have a glass of water with break...,Step 1: John drinks a glass of water with brea...,24.0,John has 4 glasses of water a day on each of t...,26,False,-31.637407,"{'Step 1:': -0.1937955666, 'Step 2:': -0.18177...",
14,Tom plants 10 trees a year. Every year he als...,Step 1: Calculate the net number of trees Tom ...,105.0,He gets 10-2=<<10-2=8>>8 new trees a year\nAft...,91,False,-30.828346,"{'Step 1:': -0.179224042, 'Step 2:': -0.170633...",
16,Brinley is in Mr. Bert's math class. Mr. Bert ...,"Step 1: First, we calculate the total score Br...",27.0,"First, identify the lowest score, which is 71,...",98,False,-43.051288,"{'Step 1:': -0.2603487783, 'Step 2:': -0.28998...",
19,Ram uses a lot of pens. He discovered that he ...,Step 1: Ram starts with 25 pens. \n\nStep 2: S...,30.0,He can make 5 pens when the 25 run low because...,31,False,-21.282201,"{'Step 1:': -0.09594150100000001, 'Step 2:': -...",
21,Mike was a pen pal with 5 people. He stopped ...,Step 1: Mike initially had 5 pen pals but stop...,2.0,He is penpals with 5-2=<<5-2=3>>3 people\nThus...,3,False,-35.318946,"{'Step 1:': -0.1526942127, 'Step 2:': -0.18656...",
22,There are 4 snails in one aquarium and 32 snai...,"Step 1: First, we find the difference in the n...",14.0,The difference between the number of snails is...,7,False,-25.676587,"{'Step 1:': -0.1311712353, 'Step 2:': -0.12046...",

In [178]:
gsm_selected_df['reasoning_steps'][22]
gsm_selected_df['paragraph_reasoning'][22] = "First, we find the difference in the number of snails between the two aquariums. There are 32 snails in the second aquarium and 4 snails in the first aquarium. The difference is 32 - 4 = 28 snails. We know that this difference (28 snails) is twice the amount of fish in both aquariums combined. Let the number of fish in each aquarium be represented as F. Therefore, the total number of fish in both aquariums is 2F. According to the problem, we can set up the equation: 28 = 2F. To find the number of fish in each aquarium, we solve for F: F = 28 / 2 = 14. Since F represents the number of fish in each aquarium, there are 14 fish in the first aquarium and 14 fish in the second aquarium."

C:\Users\li290\AppData\Local\Temp\ipykernel_21460\805716490.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gsm_selected_df['paragraph_reasoning'][22] = "First, we find the difference in the number of snails between the two aquariums. There are 32 snails in the second aquarium and 4 snails in the first aquarium. The difference is 32 - 4 = 28 snails. We know that this difference (28 snails) is twice the amount of fish in both aquariums combined. Let the number of fish in each aquarium be represented as F. Therefore, the total number of fish in both aquariums is 2F. According to the problem, we can set up the equation: 28 = 2F. To find the number of fish in each aquarium, we solve for F: F = 28 / 2 = 14. Since F represents the number of fish in each aquarium, there are 14 fish in the first aquarium and 14 fish in the second aquarium."

In [180]:
gsm_selected_df
gsm_selected_df.to_json("GSM8K_selected_incorrect_questions.jsonl", orient="records", lines=True)

In [32]:
gsm_all_df = pd.read_json("GSM8Kgsm8k_test_questions_with_logprob.jsonl", lines=True)
math_all_df = pd.read_json("MATH_test_questions_with_logprob.jsonl", lines=True)

math_all_df

,category,question,reasoning_steps,model_answer,level,log_probabilities,gt_solution,correct_answer,is_correct,total_log_prob,stepwise_log_probs
0,counting_and_probability,$n$ fair 6-sided dice are simultaneously rolle...,Step 1: Let's define the problem in terms of p...,Answer not found,4,"[{'token': 'Step', 'logprob': -0.1342868656}, ...","For $n$ dice, there are $\binom{n}{2}=\frac{n(...",4.0,False,-93.624027,"{'Step 1:': -0.24121332510000001, 'Step 2:': -..."
1,counting_and_probability,"Our club has 20 members, 10 boys and 10 girls....","Step 1: We have 20 members in the club, and we...",380.0,2,"[{'token': 'Step', 'logprob': -0.063688457}, {...",The president can be any one of the 20 members...,380.0,True,-23.195666,"{'Step 1:': -0.2559441289, 'Step 2:': -0.22508..."
2,counting_and_probability,When rolling a certain unfair six-sided die wi...,Step 1: Let's denote the probability of obtain...,289.0,5,"[{'token': 'Step', 'logprob': -0.5457024574}, ...","Let $p(a,b)$ denote the probability of obtaini...",29.0,False,-128.082638,"{'Step 1:': -0.1453271709, 'Step 2:': -0.15383..."
3,counting_and_probability,How many numbers between 1 and 2005 are intege...,"Step 1: First, determine how many numbers betw...",835.0,4,"[{'token': 'Step', 'logprob': -0.1035569087}, ...","Since $\frac{2005}{3} = 668\frac13$, there are...",835.0,True,-29.017984,"{'Step 1:': -0.2131949319, 'Step 2:': -0.12588..."
4,counting_and_probability,Amy's grandmother gave her 3 identical chocola...,"Step 1: First, calculate the total number of w...",25.0,5,"[{'token': 'Step', 'logprob': -0.0431665815}, ...",We can solve this using complementary counting...,25.0,True,-52.995049,"{'Step 1:': -0.20412378080000002, 'Step 2:': -..."
...,...,...,...,...,...,...,...,...,...,...,...
763,number_theory,What is the 453rd digit to the right of the de...,"Step 1: First, we need to find the decimal exp...",1.0,2,"[{'token': 'Step', 'logprob': -0.2130003273000...",The decimal representation of $\frac{6}{13}$ i...,1.0,True,-33.359058,"{'Step 1:': -0.1010538153, 'Step 2:': -0.24568..."
764,number_theory,"A textbook has 1,000 pages. How many of the p...",Step 1: We need to find the page numbers betwe...,18.0,5,"[{'token': 'Step', 'logprob': -0.1082122996}, ...","There are only a few ways to make one, two, an...",15.0,False,-67.825493,"{'Step 1:': -0.2787903514, 'Step 2:': -0.27292..."
765,number_theory,What is the largest number $k$ less than 1000 ...,Step 1: We need to find the largest number \( ...,841.0,4,"[{'token': 'Step', 'logprob': -0.0460917428}, ...",We can re-write the requirements of this probl...,841.0,True,-55.129722,"{'Step 1:': -0.050518911, 'Step 2:': -0.096263..."
766,number_theory,Two positive integers each have a units digit ...,"Step 1: In base 4, the units digit of a number...",0.0,4,"[{'token': 'Step', 'logprob': -0.0310456716}, ...","Since $2_4 \cdot 2_4 = 10_4$, the units digit ...",0.0,True,-20.633414,"{'Step 1:': -0.1849768819, 'Step 2:': -0.18110..."
767,number_theory,"Find the integer $n$, $0 \le n \le 5$, that sa...","Step 1: To find \( n \equiv 12345 \pmod{6} \),...",3.0,2,"[{'token': 'Step', 'logprob': -0.1343314648}, ...","When 12345 is divided by 6, the remainder is 3...",3.0,True,-33.907547,"{'Step 1:': -0.1102250444, 'Step 2:': -0.08991..."

In [45]:
correct_df = gsm_all_df[gsm_all_df["is_correct"] == True]

columns_to_keep = [
    "question", "reasoning_steps", "model_answer", "log_probabilities",
    "gt_solution", "correct_answer", "is_correct",
    "total_log_prob", "stepwise_log_probs"
]

filtered_df = correct_df[columns_to_keep]

# Step 3: Randomly sample 8 rows
gsm_sampled_df = filtered_df.sample(n=8, random_state=42)
gsm_sampled_df["paragraph_reasoning"] = ""
# gsm_sampled_df.to_json("GSM8K_selected_correct_questions.jsonl", orient="records", lines=True)
gsm_sampled_df

,question,reasoning_steps,model_answer,log_probabilities,gt_solution,correct_answer,is_correct,total_log_prob,stepwise_log_probs,paragraph_reasoning
1020,John picks 4 bananas on Wednesday. Then he pic...,"Step 1: On Wednesday, John picks 4 bananas. \n...",22.0,"[{'token': 'Step', 'logprob': -0.0073638256}, ...","Combining Wednesday and Thursday, John has 4 b...",22,True,-10.160249,"{'Step 1:': -0.0776833458, 'Step 2:': -0.09464...",
351,April is donating plant pots to a local school...,Step 1: The school asks for 30 plant pots for ...,10.0,"[{'token': 'Step', 'logprob': -0.013452432}, {...","For the roses, the school wants 30 * 2 = <<30*...",10,True,-18.069491,"{'Step 1:': -0.0764806737, 'Step 2:': -0.10620...",
109,A local gas station is selling gas for $3.00 a...,Step 1: Calculate the total cost of 10 gallons...,28.0,"[{'token': 'Step', 'logprob': -0.0081104870000...",Gas is $3.00 a gallon and they buy 10 gallons ...,28,True,-13.934245,"{'Step 1:': -0.1208979024, 'Step 2:': -0.12200...",
1019,"On a busy Saturday morning, a hotel was comple...",Step 1: Start with the initial number of guest...,98.0,"[{'token': 'Step', 'logprob': -0.012764259}, {...",24 guests checked out early and 15 checked out...,98,True,-22.794639,"{'Step 1:': -0.0785606863, 'Step 2:': -0.15180...",
61,Janet buys a brooch for her daughter. She pay...,"Step 1: First, we calculate the total cost of ...",1430.0,"[{'token': 'Step', 'logprob': -0.0139890790000...",The total cost of the broch was 500+800=$<<500...,1430,True,-18.920809,"{'Step 1:': -0.240875733, 'Step 2:': -0.174286...",
874,Ella earned $33 for 3 hours of dog walking. If...,"Step 1: First, we determine Ella's earnings pe...",132.0,"[{'token': 'Step', 'logprob': -0.0038208608}, ...",Ella earned $33 / 3 hours of dog walking = $<<...,132,True,-14.429284,"{'Step 1:': -0.162750051, 'Step 2:': -0.140063...",
1051,Ingrid drinks 8 cups of water every day. If t...,"Step 1: First, we need to calculate how many c...",15.0,"[{'token': 'Step', 'logprob': -0.0059571224000...",She drinks 8 cups of water a day so after 30 d...,15,True,-13.757998,"{'Step 1:': -0.17176034980000002, 'Step 2:': -...",
1075,Jenny goes to the florist to buy some flowers....,"Step 1: First, we calculate the cost of 15 ros...",16.0,"[{'token': 'Step', 'logprob': -0.02217302}, {'...",Jenny has $25 because 5 x 5 = <<5*5=25>>25\nSh...,16,True,-34.061282,"{'Step 1:': -0.18228241820000002, 'Step 2:': -...",

In [65]:
gsm_sampled_df["reasoning_steps"][1075]
gsm_sampled_df["paragraph_reasoning"][1075] = "First, we calculate the cost of 15 roses. Since a dozen (12 roses) costs $15, we can find the cost of 3 additional roses at $2 each. The cost for 3 roses is 3 * $2 = $6. Therefore, the total cost for 15 roses is $15 + $6 = $21. Jenny arrived with five $5 bills, which totals 5 * $5 = $25. Now, we find out how much money Jenny has left after buying the roses. She spent $21, so the remaining amount is $25 - $21 = $4. To find out how many quarters Jenny leaves with, we convert the remaining amount into quarters. Since there are 4 dollars and each dollar is equivalent to 4 quarters, we have 4 * 4 = 16 quarters."

C:\Users\li290\AppData\Local\Temp\ipykernel_21460\406293449.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gsm_sampled_df["paragraph_reasoning"][1075] = "First, we calculate the cost of 15 roses. Since a dozen (12 roses) costs $15, we can find the cost of 3 additional roses at $2 each. The cost for 3 roses is 3 * $2 = $6. Therefore, the total cost for 15 roses is $15 + $6 = $21. Jenny arrived with five $5 bills, which totals 5 * $5 = $25. Now, we find out how much money Jenny has left after buying the roses. She spent $21, so the remaining amount is $25 - $21 = $4. To find out how many quarters Jenny leaves with, we convert the remaining amount into quarters. Since there are 4 dollars and each dollar is equivalent to 4 quarters, we have 4 * 4 = 16 quarters."

In [67]:
gsm_sampled_df
gsm_sampled_df.to_json("GSM8K_selected_correct_questions.jsonl", orient="records", lines=True)

In [69]:
correct_df = math_all_df[
    (math_all_df["is_correct"] == True) & 
    (math_all_df["category"] == "counting_and_probability") &
    (math_all_df["level"] >= 4)
]

columns_to_keep = [
    "question", "reasoning_steps", "model_answer", "log_probabilities",
    "gt_solution", "correct_answer", "is_correct",
    "total_log_prob", "stepwise_log_probs"
]

filtered_df = correct_df[columns_to_keep]

# Step 3: Randomly sample 8 rows
math_sampled_df = filtered_df.sample(n=8, random_state=42)
# math_sampled_df.to_json("MATH_selected_correct_questions.jsonl", orient="records", lines=True)
math_sampled_df["paragraph_reasoning"] = ""
math_sampled_df

,question,reasoning_steps,model_answer,log_probabilities,gt_solution,correct_answer,is_correct,total_log_prob,stepwise_log_probs,paragraph_reasoning
264,"Six cars pull up to a red light, one at a time...",Step 1: We have six distinguishable cars and t...,540.0,"[{'token': 'Step', 'logprob': -0.2951034904}, ...",We count the number of ways that some lane can...,540.0,True,-81.289667,"{'Step 1:': -0.2967362038, 'Step 2:': -0.23990...",
3,How many numbers between 1 and 2005 are intege...,"Step 1: First, determine how many numbers betw...",835.0,"[{'token': 'Step', 'logprob': -0.1035569087}, ...","Since $\frac{2005}{3} = 668\frac13$, there are...",835.0,True,-29.017984,"{'Step 1:': -0.2131949319, 'Step 2:': -0.12588...",
235,In the $n$th row of Pascal's Triangle where th...,"Step 1: In Pascal's Triangle, the \( n \)th ro...",9.0,"[{'token': 'Step', 'logprob': -0.0634198561}, ...",The arithmetic mean equals the sum of the elem...,9.0,True,-63.418245,"{'Step 1:': -0.12690238680000002, 'Step 2:': -...",
72,An international meeting is held between Engla...,Step 1: Since representatives from the same co...,576.0,"[{'token': 'Step', 'logprob': -0.0302605405000...","To begin, consider the number of ways to arran...",576.0,True,-44.111255,"{'Step 1:': -0.2175439723, 'Step 2:': -0.22733...",
36,"When Trilisa takes pictures, they turn out wit...",Step 1: Let \( n \) be the number of pictures ...,7.0,"[{'token': 'Step', 'logprob': -0.0267206691}, ...",The probability that at least one picture turn...,7.0,True,-36.673659,"{'Step 1:': -0.08987777300000001, 'Step 2:': -...",
279,"How many triples $(a,b,c)$ of even positive in...","Step 1: Since \(a\), \(b\), and \(c\) are even...",35.0,"[{'token': 'Step', 'logprob': -0.156748727}, {...","If $a \geq 4$, then $a^3+b^2+c>a^3\geq 4^3>50$...",35.0,True,-72.925428,"{'Step 1:': -0.0911505757, 'Step 2:': -0.08164...",
31,Ten circles are all the same size. Each pair o...,Step 1: To find the greatest possible total nu...,90.0,"[{'token': 'Step', 'logprob': -0.0338593721}, ...",We first note that each circle can intersect a...,90.0,True,-26.598412,"{'Step 1:': -0.3374699806, 'Step 2:': -0.26920...",
59,200 points are equally spaced on the circumfer...,Step 1: To form a square using points on a cir...,50.0,"[{'token': 'Step', 'logprob': -0.1101702228000...","For any given one of the 200 points, we can fi...",50.0,True,-89.244666,"{'Step 1:': -0.4197551043, 'Step 2:': -0.32698...",

In [95]:
math_sampled_df["reasoning_steps"][59]
math_sampled_df["paragraph_reasoning"][59] = "To form a square using points on a circle, the points must be evenly spaced around the circle such that the angle between consecutive points is a multiple of 90 degrees. Since there are 200 points, the angle between consecutive points is \\( \\frac{360}{200} = 1.8 \\) degrees. For a square, the angle between two adjacent vertices must be 90 degrees. Therefore, we need to find how many times 90 degrees can be achieved by moving around the circle in steps of 1.8 degrees. Calculate the number of steps needed to achieve 90 degrees: \\( \\frac{90}{1.8} = 50 \\). This means that every 50th point from a starting point will form a square with the starting point. Since the circle is symmetric, starting from any of the 200 points and moving in steps of 50 points will form a square. However, each square is counted 4 times (once for each vertex as the starting point), so we need to divide the total by 4 to avoid overcounting. The number of squares is therefore \\( \\frac{200}{4} = 50 \\)."

C:\Users\li290\AppData\Local\Temp\ipykernel_21460\2465486290.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  math_sampled_df["paragraph_reasoning"][59] = "To form a square using points on a circle, the points must be evenly spaced around the circle such that the angle between consecutive points is a multiple of 90 degrees. Since there are 200 points, the angle between consecutive points is \\( \\frac{360}{200} = 1.8 \\) degrees. For a square, the angle between two adjacent vertices must be 90 degrees. Therefore, we need to find how many times 90 degrees can be achieved by moving around the circle in steps of 1.8 degrees. Calculate the number of steps needed to achieve 90 degrees: \\( \\frac{90}{1.8} = 50 \\). This means that every 50th point from a starting point will form a square with the starting point. Since the circle is symmetric, starting from any of the 200 points and moving in steps of 50 points will form a square. However, each square is counted 4 times (once for each vertex as the starting point), so we need to divide the total by 4 to avoid overcounting. The number of squares is therefore \\( \\frac{200}{4} = 50 \\)."

In [97]:
math_sampled_df
math_sampled_df.to_json("MATH_selected_correct_questions.jsonl", orient="records", lines=True)

In [33]:
gsm_wrong_train_id = [1, 3, 5]
math_wrong_train_id = [1, 2, 3]

gsm_correct_train_id = [1020, 351, 109]
math_correct_train_id = [264, 3, 235]

gsm_correct_test_id = [1019, 61, 874, 1051, 1075]
math_correct_train_id = [72, 36, 279, 31, 59]


gsm_correct_sel = pd.read_json("GSM8K_selected_correct_questions.jsonl", lines=True)
gsm_incorrect_sel = pd.read_json("GSM8K_selected_incorrect_questions.jsonl", lines=True)
example_df = pd.read_json("examples.json")

math_correct_sel = pd.read_json("MATH_selected_correct_questions.jsonl", lines=True)
math_incorrect_sel = pd.read_json("Math_selected_incorrect_questions.jsonl", lines=True)

In [ ]:
gsm_correct_sel
gsm_incorrect_sel
math_incorrect_sel
math_correct_sel
# example_df

In [24]:
df = pd.read_json("training_questions.jsonl", lines=True)
df

,question,reasoning_steps,model_answer,log_probabilities,gt_solution,correct_answer,is_correct,total_log_prob,stepwise_log_probs,paragraph_reasoning,Analysis,Erroneous steps
0,John picks 4 bananas on Wednesday. Then he pic...,"Step 1: On Wednesday, John picks 4 bananas. \n...",22.00,"[{'token': 'Step', 'logprob': -0.0073638256}, ...","Combining Wednesday and Thursday, John has 4 b...",22,True,-10.160249,"{'Step 1:': -0.0776833458, 'Step 2:': -0.09464...","On Wednesday, John picks 4 bananas. The next d...",None,None
1,"Six cars pull up to a red light, one at a time...",Step 1: We have six distinguishable cars and t...,540.00,"[{'token': 'Step', 'logprob': -0.2951034904}, ...",We count the number of ways that some lane can...,540,True,-81.289667,"{'Step 1:': -0.2967362038, 'Step 2:': -0.23990...",We have six distinguishable cars and three lan...,None,None
2,Carlos is planting a lemon tree. The tree will...,"Step 1: First, we calculate the total income C...",12.00,None,He makes $10.5 selling lemons each year becaus...,13,False,-40.568187,"{'Step 1:': -0.2693612289, 'Step 2:': -0.21580...","First, we calculate the total income Carlos ea...",Erroneous steps: \nThe error occurs in the int...,Erroneous steps: \nThe error occurs in the int...
3,A company pays each of its employees $600 in a...,Step 1: Sylvie's initial monthly salary is $60...,10541.52,None,"In a month, Sylvie earns $600. which totals $6...",9360,False,-55.998108,"{'Step 1:': -0.1382282676, 'Step 2:': -0.21145...",Sylvie's initial monthly salary is $600. To fi...,Erroneous steps: Step 4 and beyond.\n\nExplana...,Erroneous steps: Step 4 and beyond.\n\n
4,Ingrid drinks 8 cups of water every day. If t...,"Step 1: First, we need to calculate how many c...",15.00,"[{'token': 'Step', 'logprob': -0.0059571224000...",She drinks 8 cups of water a day so after 30 d...,15,True,-13.757998,"{'Step 1:': -0.17176034980000002, 'Step 2:': -...","First, we need to calculate how many cups of w...",None,None
5,When rolling a certain unfair six-sided die wi...,Step 1: Let's denote the probability of obtain...,17.00,None,"Let $p(a,b)$ denote the probability of obtaini...",29,False,-181.785633,"{'Step 1:': -0.2135267627, 'Step 2:': -0.15305...",Let's denote the probability of obtaining face...,Erroneous steps:\n \n**Step 18**: The error b...,Erroneous steps:\n \n**Step 18**: The error b...

In [43]:
gsm_correct_sel = pd.read_json("GSM8K_selected_correct_questions.jsonl", lines=True)
gsm_incorrect_sel = pd.read_json("GSM8K_selected_incorrect_questions.jsonl", lines=True)

math_correct_sel = pd.read_json("MATH_selected_correct_questions.jsonl", lines=True)
math_incorrect_sel = pd.read_json("Math_selected_incorrect_questions.jsonl", lines=True)

train = pd.read_json("training_questions.jsonl", lines=True)

# Add the "dataset" column with the appropriate value for each DataFrame
gsm_correct_sel["dataset"] = "gsm8k"
gsm_incorrect_sel["dataset"] = "gsm8k"

math_correct_sel["dataset"] = "math"
math_incorrect_sel["dataset"] = "math"

In [ ]:
combined_df = pd.concat(
    [gsm_correct_sel, gsm_incorrect_sel, math_correct_sel, math_incorrect_sel],
    ignore_index=True
)

combined_df = combined_df.sample(frac=1, random_state=42).reset_index(drop=True)
combined_df

In [ ]:
combined_df = pd.read_json("question_bank.jsonl", lines=True)
combined_df

train["dataset"] = "train"

In [47]:
final_df = pd.concat([train, combined_df], ignore_index=True)
final_df.to_json("question_bank.jsonl", orient="records", lines=True)
final_df

,question,reasoning_steps,model_answer,log_probabilities,gt_solution,correct_answer,is_correct,total_log_prob,stepwise_log_probs,paragraph_reasoning,Analysis,Erroneous steps,dataset,question_id,category,level
0,John picks 4 bananas on Wednesday. Then he pic...,"Step 1: On Wednesday, John picks 4 bananas. \n...",2.200000e+01,"[{'token': 'Step', 'logprob': -0.0073638256}, ...","Combining Wednesday and Thursday, John has 4 b...",22,True,-10.160249,"{'Step 1:': -0.0776833458, 'Step 2:': -0.09464...","On Wednesday, John picks 4 bananas. The next d...",None,None,train,NaN,NaN,NaN
1,"Six cars pull up to a red light, one at a time...",Step 1: We have six distinguishable cars and t...,5.400000e+02,"[{'token': 'Step', 'logprob': -0.2951034904}, ...",We count the number of ways that some lane can...,540,True,-81.289667,"{'Step 1:': -0.2967362038, 'Step 2:': -0.23990...",We have six distinguishable cars and three lan...,None,None,train,NaN,NaN,NaN
2,Carlos is planting a lemon tree. The tree will...,"Step 1: First, we calculate the total income C...",1.200000e+01,None,He makes $10.5 selling lemons each year becaus...,13,False,-40.568187,"{'Step 1:': -0.2693612289, 'Step 2:': -0.21580...","First, we calculate the total income Carlos ea...",Erroneous steps: \nThe error occurs in the int...,Erroneous steps: \nThe error occurs in the int...,train,NaN,NaN,NaN
3,A company pays each of its employees $600 in a...,Step 1: Sylvie's initial monthly salary is $60...,1.054152e+04,None,"In a month, Sylvie earns $600. which totals $6...",9360,False,-55.998108,"{'Step 1:': -0.1382282676, 'Step 2:': -0.21145...",Sylvie's initial monthly salary is $600. To fi...,Erroneous steps: Step 4 and beyond.\n\nExplana...,Erroneous steps: Step 4 and beyond.\n\n,train,NaN,NaN,NaN
4,Ingrid drinks 8 cups of water every day. If t...,"Step 1: First, we need to calculate how many c...",1.500000e+01,"[{'token': 'Step', 'logprob': -0.0059571224000...",She drinks 8 cups of water a day so after 30 d...,15,True,-13.757998,"{'Step 1:': -0.17176034980000002, 'Step 2:': -...","First, we need to calculate how many cups of w...",None,None,train,NaN,NaN,NaN
5,When rolling a certain unfair six-sided die wi...,Step 1: Let's denote the probability of obtain...,1.700000e+01,None,"Let $p(a,b)$ denote the probability of obtaini...",29,False,-181.785633,"{'Step 1:': -0.2135267627, 'Step 2:': -0.15305...",Let's denote the probability of obtaining face...,Erroneous steps:\n \n**Step 18**: The error b...,Erroneous steps:\n \n**Step 18**: The error b...,train,NaN,NaN,NaN
6,A $4\times 4\times 4$ open cubical box contain...,Step 1: Consider the structure of the $4 \time...,6.400000e+01,None,We count the complement. A cube that does not ...,52,False,-99.537313,"{'Step 1:': -0.3682932598, 'Step 2:': -0.33891...",Consider the structure of the \( 4 \times 4 \t...,NaN,NaN,math,38.0,counting_and_probability,4.0
7,How many numbers between 1 and 2005 are intege...,"Step 1: First, determine how many numbers betw...",8.350000e+02,"[{'token': 'Step', 'logprob': -0.1035569087}, ...","Since $\frac{2005}{3} = 668\frac13$, there are...",835,True,-29.017984,"{'Step 1:': -0.2131949319, 'Step 2:': -0.12588...","First, determine how many numbers between 1 an...",NaN,NaN,math,NaN,None,NaN
8,"The letters $A, B$ and $C$ are used to form ev...",Step 1: We need to determine the position of t...,1.400000e+01,None,There are 9 possible words that start with A t...,11,False,-63.576446,"{'Step 1:': -0.20251417100000002, 'Step 2:': -...",We need to determine the position of the word ...,NaN,NaN,math,18.0,counting_and_probability,2.0
9,"How many triples $(a,b,c)$ of even positive in...","Step 1: Since \(a\), \(b\), and \(c\) are even...",3.500000e+01,"[{'token': 'Step', 'logprob': -0.156748727}, {...","If $a \geq 4$, then $a^3+b^2+c>a^3\geq 4^3>50$...",35,True,-72.925428,"{'Step 1:': -0.0911505757, 'Step 2:': -0.08164...","Since \(a\), \(b\), and \(c\) are even positiv...",NaN,NaN,math,NaN,None,NaN
10,Christina is planning a birthday party and nee...,"Step 1: First, we need to determine how many g...",1.800000e+01,None,She needs 12 gift bags because 16 x .75 = <<16...,24,False,-26.217186,"{'Step 1:': -0.2306994265, 'Step 2:': -0.18537...","First, we need to determine how many guests Ch...",NaN,NaN,gsm8k,NaN,None,NaN
11,John likes to have a glass of water with break...,Step 1: John drinks a glass of water with brea...,2.400000e+01,None,John has 4 glasses of water a day on each of t...,26,False,-31.637407,"{'Step 1:': -0.1937955666, 'Step 2:': -0.18177...","John drinks a glass of water with breakfast, l...",NaN,NaN,gsm8k,NaN,None,NaN
12,How many of the natural numbers from $1$ to $8...,Step 1: We need to find the number of natural ...,2.800000e+01,None,There are $10$ numbers with a $6$ in the hundr...,26,False,-71.215213,"{'Step 1:': -0.2251759852, 'Step 2:': -0.26338...",We need to find the number of natural numbers ...,NaN,NaN,math,57.0,counting_and_probability,4.0
13,When a fair six-sided die is tossed on a table...,Step 1: A fair six-sided die has faces numbere...,8.333000e-01,None,"If 6 is one of the visible faces, the product ...",1,False,-96.622040,"{'Step 1:': -0.2463127193, 'Step 2:': -0.17836...",A fair six-sided die has faces numbered 1 thro...,NaN,NaN,math,28.0,counting_and_probability,3.0
14,Ram uses a lot of pens. He discovered that he ...,Step 1: Ram starts with 25 pens. \n\nStep 2: S...,3.000000e+01,None,He can make 5 pens when the 25 run low because...,31,False,-21.282201,"{'Step 1:': -0.09594150100000001, 'Step 2:': -...",Ram starts with 25 pens. Since he can mix the ...,NaN,NaN,gsm8k,NaN,None,NaN
15,April is donating plant pots to a local school...,Step 1: The school asks for 30 plant pots for ...,1.000000e+01,"[{'token': 'Step', 'logprob': -0.013452432}, {...","For the roses, the school wants 30 * 2 = <<30*...",10,True,-18.069491,"{'Step 1:': -0.0764806737, 'Step 2:': -0.10620...",The school needs 30 plant pots for the daisies...,NaN,NaN,gsm8k,NaN,None,NaN
16,Jenny goes to the florist to buy some flowers....,"Step 1: First, we calculate the cost of 15 ros...",1.600000e+01,"[{'token': 'Step', 'logprob': -0.02217302}, {'...",Jenny has $25 because 5 x 5 = <<5*5=25>>25\nSh...,16,True,-34.061282,"{'Step 1:': -0.18228241820000002, 'Step 2:': -...","First, we calculate the cost of 15 roses. Sinc...",NaN,NaN,gsm8k,NaN,None,NaN
17,In the $n$th row of Pascal's Triangle where th...,"Step 1: In Pascal's Triangle, the \( n \)th ro...",9.000000e+00,"[{'token': 'Step', 'logprob': -0.0634198561}, ...",The arithmetic mean equals the sum of the elem...,9,True,-63.418245,"{'Step 1:': -0.12690238680000002, 'Step 2:': -...","In Pascal's Triangle, the nth row has n+1 elem...",NaN,NaN,math,NaN,None,NaN
18,Carla is downloading a 200 GB file. Normally s...,"Step 1: First, we need to determine how much o...",1.200000e+02,None,First find how many gigabytes are in 40% of th...,160,False,-44.422417,"{'Step 1:': -0.2185396467, 'Step 2:': -0.21152...","First, we need to determine how much of the fi...",NaN,NaN,gsm8k,NaN,None,NaN
19,Mike was a pen pal with 5 people. He stopped ...,Step 1: Mike initially had 5 pen pals but stop...,2.000000e+00,None,He is penpals with 5-2=<<5-2=3>>3 people\nThus...,3,False,-35.318946,"{'Step 1:': -0.1526942127, 'Step 2:': -0.18656...",Mike initially had 5 pen pals but stopped bein...,NaN,NaN,gsm8k,NaN,None,NaN
20,Brinley is in Mr. Bert's math class. Mr. Bert ...,"Step 1: First, we calculate the total score Br...",2.700000e+01,None,"First, identify the lowest score, which is 71,...",98,False,-43.051288,"{'Step 1:': -0.2603487783, 'Step 2:': -0.28998...","First, we calculate the total score Brinley ne...",NaN,NaN,gsm8k,NaN,None,NaN
21,"A street has 50 houses on each side, for a tot...",Step 1: Determine the sequence of house number...,2.460000e+02,None,If we combine the house numbers on the north a...,245,False,-70.004683,"{'Step 1:': -0.1912033286, 'Step 2:': -0.15656...",Determine the sequence of house numbers on the...,NaN,NaN,math,11.0,counting_and_probability,4.0
22,A local gas station is selling gas for $3.00 a...,Step 1: Calculate the total cost of 10 gallons...,2.800000e+01,"[{'token': 'Step', 'logprob': -0.0081104870000...",Gas is $3.00 a gallon and they buy 10 gallons ...,28,True,-13.934245,"{'Step 1:': -0.1208979024, 'Step 2:': -0.12200...","To start, the total cost of 10 gallons of gas ...",NaN,NaN,gsm8k,NaN,None,NaN
23,"On a busy Saturday morning, a hotel was comple...",Step 1: Start with the initial number of guest...,9.800000e+01,"[{'token': 'Step', 'logprob': -0.012764259}, {...",24 guests checked out early and 15 checked out...,98,True,-22.794639,"{'Step 1:': -0.0785606863, 'Step 2:': -0.15180...","The hotel starts with 100 guests. First, we su...",NaN,NaN,gsm8k,NaN,None,NaN
24,Kim has $10$ identical lamps and $3$ identical...,Step 1: We need to distribute 10 identical lam...,6.600000e+01,None,Only the number of lamps on each table matters...,14,False,-30.274828,"{'Step 1:': -0.21624543840000002, 'Step 2:': -...",We need to distribute 10 identical lamps acros...,NaN,NaN,math,29.0,counting_and_probability,5.0
25,Janet buys a brooch for her daughter. She pay...,"Step 1: First, we calculate the total cost of ...",1.430000e+03,"[{'token': 'Step', 'logprob': -0.0139890790000...",The total cost of the broch was 500+800=$<<500...,1430,True,-18.920809,"{'Step 1:': -0.240875733, 'Step 2:': -0.174286...","First, we calculate the total cost of the mate...",NaN,NaN,gsm8k,NaN,None,NaN
26,"How many numbers are in the list $$ 6,7,10,11,...",Step 1: Observe the pattern in the sequence: t...,4.600000e+01,None,We first count the even terms of the sequence....,47,False,-57.239853,"{'Step 1:': -0.33314112220000003, 'Step 2:': -...",Observe the pattern in the sequence: the numbe...,NaN,NaN,math,10.0,counting_and_probability,3.0
27,On the student government ballot at Dusable Hi...,Step 1: Determine the number of ways to list t...,1.244160e+06,None,"Since there are six candidates for president, ...",12441600,False,-34.407995,"{'Step 1:': -0.2679094725, 'Step 2:': -0.19253...",Determine the number of ways to list the candi...,NaN,NaN,math,34.0,counting_and_probability,4.0
28,Ten circles are all the same size. Each pair o...,Step 1: To find the greatest possible total nu...,9.000000e+01,"[{'token': 'Step', 'logprob': -0.0338593721}, ...",We first note that each circle can intersect a...,90,True,-26.598412,"{'Step 1:': -0.3374699806, 'Step 2:': -0.26920...",To find the greatest possible total number of ...,NaN,NaN,math,NaN,None,NaN
29,Each digit in the number 2001 is placed on a d...,Step 1: The number 2001 consists of the digits...,1.000000e+00,None,"There are four cards total, two of which have ...",0,False,-71.435032,"{'Step 1:': -0.0710904223, 'Step 2:': -0.17621...","The number 2001 consists of the digits 2, 0, 0...",NaN,NaN,math,58.0,counting_and_probability,2.0
30,The increasing list of five different integers...,Step 1: We need to find increasing lists of fi...,1.000000e+01,None,"After some trial and error, we obtain the two ...",2,False,-89.047330,"{'Step 1:': -0.14934915040000002, 'Step 2:': -...",We need to find increasing lists of five diffe...,NaN,NaN,math,8.0,counting_and_probability,4.0
31,Luke is spending time at the beach building sa...,Step 1: The top level of the sandcastle has a ...,7.500000e+00,None,Level 3 is 32 square feet because 16 x 2 = <<1...,60,False,-15.143888,"{'Step 1:': -0.0866175044, 'Step 2:': -0.09407...",The top level of the sandcastle has a square f...,NaN,NaN,gsm8k,NaN,None,NaN
32,Tom plants 10 trees a year. Every year he als...,Step 1: Calculate the net number of trees Tom ...,1.050000e+02,None,He gets 10-2=<<10-2=8>>8 new trees a year\nAft...,91,False,-30.828346,"{'Step 1:': -0.179224042, 'Step 2:': -0.170633...",Calculate the net number of trees Tom plants e...,NaN,NaN,gsm8k,NaN,None,NaN
33,There are 4 snails in one aquarium and 32 snai...,"Step 1: First, we find the difference in the n...",1.400000e+01,None,The difference between the number of snails is...,7,False,-25.676587,"{'Step 1:': -0.1311712353, 'Step 2:': -0.12046...","First, we find the difference in the number of...",NaN,NaN,gsm8k,NaN,None,NaN
34,How many numbers can be expressed as the sum o...,"Step 1: The set given is \(\{0, 1, 2, 4, 8, 16...",2.900000e+01,None,"We see that the given numbers, expressed in bi...",31,False,-103.442798,"{'Step 1:': -0.1935318285, 'Step 2:': -0.28084...","The set given is \( \{0, 1, 2, 4, 8, 16\} \). ...",NaN,NaN,math,46.0,counting_and_probability,5.0
35,200 points are equally spaced on the circumfer...,Step 1: To form a square using points on a cir...,5.000000e+01,"[{'token': 'Step', 'logprob': -0.1101702228000...","For any given one of the 200 points, we can fi...",50,True,-89.244666,"{'Step 1:': -0.4197551043, 'Step 2:': -0.32698...","To form a square using points on a circle, the...",NaN,NaN,math,NaN,None,NaN
36,John plans to sell all his toys and use the mo...,Step 1: Calculate the total amount of money Jo...,0.000000e+00,None,He spent $160 on video games because 8 x 20 = ...,2,False,-29.595732,"{'Step 1:': -0.1743409722, 'Step 2:': -0.13850...",Calculate the total amount of money John makes...,NaN,NaN,gsm8k,NaN,None,NaN

In [3]:
df = pd.read_json("question_bank.jsonl", lines=True)
df

,question,reasoning_steps,model_answer,log_probabilities,gt_solution,correct_answer,is_correct,total_log_prob,stepwise_log_probs,paragraph_reasoning,Analysis,Erroneous steps,dataset,question_id,category,level
0,John picks 4 bananas on Wednesday. Then he pic...,"Step 1: On Wednesday, John picks 4 bananas. \n...",2.200000e+01,"[{'token': 'Step', 'logprob': -0.0073638256}, ...","Combining Wednesday and Thursday, John has 4 b...",22,True,-10.160249,"{'Step 1:': -0.0776833458, 'Step 2:': -0.09464...","On Wednesday, John picks 4 bananas. The next d...",None,None,train,NaN,None,NaN
1,"Six cars pull up to a red light, one at a time...",Step 1: We have six distinguishable cars and t...,5.400000e+02,"[{'token': 'Step', 'logprob': -0.2951034904}, ...",We count the number of ways that some lane can...,540,True,-81.289667,"{'Step 1:': -0.2967362038, 'Step 2:': -0.23990...",We have six distinguishable cars and three lan...,None,None,train,NaN,None,NaN
2,Carlos is planting a lemon tree. The tree will...,"Step 1: First, we calculate the total income C...",1.200000e+01,None,He makes $10.5 selling lemons each year becaus...,13,False,-40.568187,"{'Step 1:': -0.2693612289, 'Step 2:': -0.21580...","First, we calculate the total income Carlos ea...",Erroneous steps: \nThe error occurs in the int...,Erroneous steps: \nThe error occurs in the int...,train,NaN,None,NaN
3,A company pays each of its employees $600 in a...,Step 1: Sylvie's initial monthly salary is $60...,1.054152e+04,None,"In a month, Sylvie earns $600. which totals $6...",9360,False,-55.998108,"{'Step 1:': -0.1382282676, 'Step 2:': -0.21145...",Sylvie's initial monthly salary is $600. To fi...,Erroneous steps: Step 4 and beyond.\n\nExplana...,Erroneous steps: Step 4 and beyond.\n\n,train,NaN,None,NaN
4,Ingrid drinks 8 cups of water every day. If t...,"Step 1: First, we need to calculate how many c...",1.500000e+01,"[{'token': 'Step', 'logprob': -0.0059571224000...",She drinks 8 cups of water a day so after 30 d...,15,True,-13.757998,"{'Step 1:': -0.17176034980000002, 'Step 2:': -...","First, we need to calculate how many cups of w...",None,None,train,NaN,None,NaN
5,When rolling a certain unfair six-sided die wi...,Step 1: Let's denote the probability of obtain...,1.700000e+01,None,"Let $p(a,b)$ denote the probability of obtaini...",29,False,-181.785633,"{'Step 1:': -0.2135267627, 'Step 2:': -0.15305...",Let's denote the probability of obtaining face...,Erroneous steps:\n \n**Step 18**: The error b...,Erroneous steps:\n \n**Step 18**: The error b...,train,NaN,None,NaN
6,A $4\times 4\times 4$ open cubical box contain...,Step 1: Consider the structure of the $4 \time...,6.400000e+01,None,We count the complement. A cube that does not ...,52,False,-99.537313,"{'Step 1:': -0.3682932598, 'Step 2:': -0.33891...",Consider the structure of the $ 4 \times 4 \ti...,None,None,math,38.0,counting_and_probability,4.0
7,How many numbers between 1 and 2005 are intege...,"Step 1: First, determine how many numbers betw...",8.350000e+02,"[{'token': 'Step', 'logprob': -0.1035569087}, ...","Since $\frac{2005}{3} = 668\frac13$, there are...",835,True,-29.017984,"{'Step 1:': -0.2131949319, 'Step 2:': -0.12588...","First, determine how many numbers between 1 an...",None,None,math,NaN,None,NaN
8,"The letters $A, B$ and $C$ are used to form ev...",Step 1: We need to determine the position of t...,1.400000e+01,None,There are 9 possible words that start with A t...,11,False,-63.576446,"{'Step 1:': -0.20251417100000002, 'Step 2:': -...",We need to determine the position of the word ...,None,None,math,18.0,counting_and_probability,2.0
9,"How many triples $(a,b,c)$ of even positive in...","Step 1: Since $a$, $b$, and $c$ are even posit...",3.500000e+01,"[{'token': 'Step', 'logprob': -0.156748727}, {...","If $a \geq 4$, then $a^3+b^2+c>a^3\geq 4^3>50$...",35,True,-72.925428,"{'Step 1:': -0.0911505757, 'Step 2:': -0.08164...","Since $a$, $b$, and $c$ are even positive inte...",None,None,math,NaN,None,NaN
10,Christina is planning a birthday party and nee...,"Step 1: First, we need to determine how many g...",1.800000e+01,None,She needs 12 gift bags because 16 x .75 = <<16...,24,False,-26.217186,"{'Step 1:': -0.2306994265, 'Step 2:': -0.18537...","First, we need to determine how many guests Ch...",None,None,gsm8k,NaN,None,NaN
11,John likes to have a glass of water with break...,Step 1: John drinks a glass of water with brea...,2.400000e+01,None,John has 4 glasses of water a day on each of t...,26,False,-31.637407,"{'Step 1:': -0.1937955666, 'Step 2:': -0.18177...","John drinks a glass of water with breakfast, l...",None,None,gsm8k,NaN,None,NaN
12,How many of the natural numbers from $1$ to $8...,Step 1: We need to find the number of natural ...,2.800000e+01,None,There are $10$ numbers with a $6$ in the hundr...,26,False,-71.215213,"{'Step 1:': -0.2251759852, 'Step 2:': -0.26338...",We need to find the number of natural numbers ...,None,None,math,57.0,counting_and_probability,4.0
13,When a fair six-sided die is tossed on a table...,Step 1: A fair six-sided die has faces numbere...,8.333000e-01,None,"If 6 is one of the visible faces, the product ...",1,False,-96.622040,"{'Step 1:': -0.2463127193, 'Step 2:': -0.17836...",A fair six-sided die has faces numbered 1 thro...,None,None,math,28.0,counting_and_probability,3.0
14,Ram uses a lot of pens. He discovered that he ...,Step 1: Ram starts with 25 pens. \n\nStep 2: S...,3.000000e+01,None,He can make 5 pens when the 25 run low because...,31,False,-21.282201,"{'Step 1:': -0.09594150100000001, 'Step 2:': -...",Ram starts with 25 pens. Since he can mix the ...,None,None,gsm8k,NaN,None,NaN
15,April is donating plant pots to a local school...,Step 1: The school asks for 30 plant pots for ...,1.000000e+01,"[{'token': 'Step', 'logprob': -0.013452432}, {...","For the roses, the school wants 30 * 2 = <<30*...",10,True,-18.069491,"{'Step 1:': -0.0764806737, 'Step 2:': -0.10620...",The school needs 30 plant pots for the daisies...,None,None,gsm8k,NaN,None,NaN
16,Jenny goes to the florist to buy some flowers....,"Step 1: First, we calculate the cost of 15 ros...",1.600000e+01,"[{'token': 'Step', 'logprob': -0.02217302}, {'...",Jenny has $25 because 5 x 5 = <<5*5=25>>25\nSh...,16,True,-34.061282,"{'Step 1:': -0.18228241820000002, 'Step 2:': -...","First, we calculate the cost of 15 roses. Sinc...",None,None,gsm8k,NaN,None,NaN
17,In the $n$th row of Pascal's Triangle where th...,"Step 1: In Pascal's Triangle, the $ n $th row ...",9.000000e+00,"[{'token': 'Step', 'logprob': -0.0634198561}, ...",The arithmetic mean equals the sum of the elem...,9,True,-63.418245,"{'Step 1:': -0.12690238680000002, 'Step 2:': -...","In Pascal's Triangle, the nth row has n+1 elem...",None,None,math,NaN,None,NaN
18,Carla is downloading a 200 GB file. Normally s...,"Step 1: First, we need to determine how much o...",1.200000e+02,None,First find how many gigabytes are in 40% of th...,160,False,-44.422417,"{'Step 1:': -0.2185396467, 'Step 2:': -0.21152...","First, we need to determine how much of the fi...",None,None,gsm8k,NaN,None,NaN
19,Mike was a pen pal with 5 people. He stopped ...,Step 1: Mike initially had 5 pen pals but stop...,2.000000e+00,None,He is penpals with 5-2=<<5-2=3>>3 people\nThus...,3,False,-35.318946,"{'Step 1:': -0.1526942127, 'Step 2:': -0.18656...",Mike initially had 5 pen pals but stopped bein...,None,None,gsm8k,NaN,None,NaN
20,Brinley is in Mr. Bert's math class. Mr. Bert ...,"Step 1: First, we calculate the total score Br...",2.700000e+01,None,"First, identify the lowest score, which is 71,...",98,False,-43.051288,"{'Step 1:': -0.2603487783, 'Step 2:': -0.28998...","First, we calculate the total score Brinley ne...",None,None,gsm8k,NaN,None,NaN
21,"A street has 50 houses on each side, for a tot...",Step 1: Determine the sequence of house number...,2.460000e+02,None,If we combine the house numbers on the north a...,245,False,-70.004683,"{'Step 1:': -0.1912033286, 'Step 2:': -0.15656...",Determine the sequence of house numbers on the...,None,None,math,11.0,counting_and_probability,4.0
22,A local gas station is selling gas for $3.00 a...,Step 1: Calculate the total cost of 10 gallons...,2.800000e+01,"[{'token': 'Step', 'logprob': -0.0081104870000...",Gas is $3.00 a gallon and they buy 10 gallons ...,28,True,-13.934245,"{'Step 1:': -0.1208979024, 'Step 2:': -0.12200...","To start, the total cost of 10 gallons of gas ...",None,None,gsm8k,NaN,None,NaN
23,"On a busy Saturday morning, a hotel was comple...",Step 1: Start with the initial number of guest...,9.800000e+01,"[{'token': 'Step', 'logprob': -0.012764259}, {...",24 guests checked out early and 15 checked out...,98,True,-22.794639,"{'Step 1:': -0.0785606863, 'Step 2:': -0.15180...","The hotel starts with 100 guests. First, we su...",None,None,gsm8k,NaN,None,NaN
24,Kim has $10$ identical lamps and $3$ identical...,Step 1: We need to distribute 10 identical lam...,6.600000e+01,None,Only the number of lamps on each table matters...,14,False,-30.274828,"{'Step 1:': -0.21624543840000002, 'Step 2:': -...",We need to distribute 10 identical lamps acros...,None,None,math,29.0,counting_and_probability,5.0
25,Janet buys a brooch for her daughter. She pay...,"Step 1: First, we calculate the total cost of ...",1.430000e+03,"[{'token': 'Step', 'logprob': -0.0139890790000...",The total cost of the broch was 500+800=$<<500...,1430,True,-18.920809,"{'Step 1:': -0.240875733, 'Step 2:': -0.174286...","First, we calculate the total cost of the mate...",None,None,gsm8k,NaN,None,NaN
26,"How many numbers are in the list $$ 6,7,10,11,...",Step 1: Observe the pattern in the sequence: t...,4.600000e+01,None,We first count the even terms of the sequence....,47,False,-57.239853,"{'Step 1:': -0.33314112220000003, 'Step 2:': -...",Observe the pattern in the sequence: the numbe...,None,None,math,10.0,counting_and_probability,3.0
27,On the student government ballot at Dusable Hi...,Step 1: Determine the number of ways to list t...,1.244160e+06,None,"Since there are six candidates for president, ...",12441600,False,-34.407995,"{'Step 1:': -0.2679094725, 'Step 2:': -0.19253...",Determine the number of ways to list the candi...,None,None,math,34.0,counting_and_probability,4.0
28,Ten circles are all the same size. Each pair o...,Step 1: To find the greatest possible total nu...,9.000000e+01,"[{'token': 'Step', 'logprob': -0.0338593721}, ...",We first note that each circle can intersect a...,90,True,-26.598412,"{'Step 1:': -0.3374699806, 'Step 2:': -0.26920...",To find the greatest possible total number of ...,None,None,math,NaN,None,NaN
29,Each digit in the number 2001 is placed on a d...,Step 1: The number 2001 consists of the digits...,1.000000e+00,None,"There are four cards total, two of which have ...",0,False,-71.435032,"{'Step 1:': -0.0710904223, 'Step 2:': -0.17621...","The number 2001 consists of the digits 2, 0, 0...",None,None,math,58.0,counting_and_probability,2.0
30,The increasing list of five different integers...,Step 1: We need to find increasing lists of fi...,1.000000e+01,None,"After some trial and error, we obtain the two ...",2,False,-89.047330,"{'Step 1:': -0.14934915040000002, 'Step 2:': -...",We need to find increasing lists of five diffe...,None,None,math,8.0,counting_and_probability,4.0
31,Luke is spending time at the beach building sa...,Step 1: The top level of the sandcastle has a ...,7.500000e+00,None,Level 3 is 32 square feet because 16 x 2 = <<1...,60,False,-15.143888,"{'Step 1:': -0.0866175044, 'Step 2:': -0.09407...",The top level of the sandcastle has a square f...,None,None,gsm8k,NaN,None,NaN
32,Tom plants 10 trees a year. Every year he als...,Step 1: Calculate the net number of trees Tom ...,1.050000e+02,None,He gets 10-2=<<10-2=8>>8 new trees a year\nAft...,91,False,-30.828346,"{'Step 1:': -0.179224042, 'Step 2:': -0.170633...",Calculate the net number of trees Tom plants e...,None,None,gsm8k,NaN,None,NaN
33,There are 4 snails in one aquarium and 32 snai...,"Step 1: First, we find the difference in the n...",1.400000e+01,None,The difference between the number of snails is...,7,False,-25.676587,"{'Step 1:': -0.1311712353, 'Step 2:': -0.12046...","First, we find the difference in the number of...",None,None,gsm8k,NaN,None,NaN
34,How many numbers can be expressed as the sum o...,"Step 1: The set given is $\{0, 1, 2, 4, 8, 16\...",2.900000e+01,None,"We see that the given numbers, expressed in bi...",31,False,-103.442798,"{'Step 1:': -0.1935318285, 'Step 2:': -0.28084...","The set given is $ \{0, 1, 2, 4, 8, 16\} $. We...",None,None,math,46.0,counting_and_probability,5.0
35,200 points are equally spaced on the circumfer...,Step 1: To form a square using points on a cir...,5.000000e+01,"[{'token': 'Step', 'logprob': -0.1101702228000...","For any given one of the 200 points, we can fi...",50,True,-89.244666,"{'Step 1:': -0.4197551043, 'Step 2:': -0.32698...","To form a square using points on a circle, the...",None,None,math,NaN,None,NaN
36,John plans to sell all his toys and use the mo...,Step 1: Calculate the total amount of money Jo...,0.000000e+00,None,He spent $160 on video games because 8 x 20 = ...,2,False,-29.595732,"{'Step 1:': -0.1743409722, 'Step 2:': -0.13850...",Calculate the total amount of money John makes...,None,None,gsm8k,NaN,None,NaN

In [4]:
gsm_wrong_train_id = [1, 3, 5]
math_wrong_train_id = [1, 2, 3]

gsm_correct_train_id = [1020, 351, 109]
math_correct_train_id = [264, 3, 235]

gsm_correct_test_id = [1019, 61, 874, 1051, 1075]
math_correct_train_id = [72, 36, 279, 31, 59]


gsm_all_df = pd.read_json("GSM8Kgsm8k_test_questions_with_logprob.jsonl", lines=True)
math_all_df = pd.read_json("MATH_test_questions_with_logprob.jsonl", lines=True)

In [13]:
gsm_correct = gsm_all_df[gsm_all_df["is_correct"] == True]
math_correct = math_all_df[math_all_df["is_correct"] == True & (math_all_df["category"] == "counting_and_probability")]

gsm_incorrect = gsm_all_df[gsm_all_df["is_correct"] == False]
math_incorrect = math_all_df[(math_all_df["is_correct"] == False) & (math_all_df["category"] == "counting_and_probability")]


gsm_cor_sel = gsm_correct.tail(2)
math_sel = math_incorrect.tail(1)
gsm_incor = gsm_incorrect.tail(1)

gsm_incorrect

,question,reasoning_steps,model_answer,log_probabilities,gt_solution,correct_answer,is_correct,total_log_prob,stepwise_log_probs
7,Carla is downloading a 200 GB file. Normally s...,"Step 1: First, we need to determine how much o...",120.0,"[{'token': 'Step', 'logprob': -0.21731956}, {'...",First find how many gigabytes are in 40% of th...,160,False,-44.422417,"{'Step 1:': -0.2185396467, 'Step 2:': -0.21152..."
12,Carlos is planting a lemon tree. The tree will...,"Step 1: First, we calculate the total income C...",12.0,"[{'token': 'Step', 'logprob': -0.05097815}, {'...",He makes $10.5 selling lemons each year becaus...,13,False,-40.568187,"{'Step 1:': -0.2693612289, 'Step 2:': -0.21580..."
37,John plans to sell all his toys and use the mo...,Step 1: Calculate the total amount of money Jo...,0.0,"[{'token': 'Step', 'logprob': -0.03342679}, {'...",He spent $160 on video games because 8 x 20 = ...,2,False,-29.595732,"{'Step 1:': -0.1743409722, 'Step 2:': -0.13850..."
62,If Marcy works for the same company for 40 yea...,Step 1: Marcy works for 40 years and is entitl...,75000.0,"[{'token': 'Step', 'logprob': -0.11307678}, {'...",First find how many years Marcy works after 20...,25000,False,-48.260233,"{'Step 1:': -0.1559471165, 'Step 2:': -0.20606..."
75,Luke is spending time at the beach building sa...,Step 1: The top level of the sandcastle has a ...,7.5,"[{'token': 'Step', 'logprob': -0.0126577390000...",Level 3 is 32 square feet because 16 x 2 = <<1...,60,False,-15.143888,"{'Step 1:': -0.0866175044, 'Step 2:': -0.09407..."
...,...,...,...,...,...,...,...,...,...
1188,Digimon had its 20th anniversary. When it cam...,Step 1: Since John is currently 28 years old a...,4.0,"[{'token': 'Step', 'logprob': -0.01995755}, {'...",When Digimon came out John would have been 28-...,24,False,-22.102785,"{'Step 1:': -0.2439483479, 'Step 2:': -0.18847..."
1199,Fred was preparing for a party to be held in f...,Step 1: Fred made 24 gallons of root beer on t...,2.67,"[{'token': 'Step', 'logprob': -0.0510175860000...","Fred started with 24 gallons, but on day 1, hi...",2,False,-21.337328,"{'Step 1:': -0.1080875666, 'Step 2:': -0.13925..."
1206,John decides to get a loan by mortgaging his h...,Step 1: Calculate the amount of the loan John ...,40000.0,"[{'token': 'Step', 'logprob': -0.0133421050000...","His loan is worth 250,000*.4=$<<250000*.4=1000...",0,False,-17.053919,"{'Step 1:': -0.2368666164, 'Step 2:': -0.17544..."
1288,Every day Charisma meditates for 15 minutes wh...,Step 1: Charisma meditates for 15 minutes in t...,2040.0,"[{'token': 'Step', 'logprob': -0.0217735840000...",She meditates for 15 minutes in the morning an...,34,False,-24.512419,"{'Step 1:': -0.1421016434, 'Step 2:': -0.20308..."
1309,The girls are trying to raise money for a carn...,"Step 1: First, we find out how much Alexandra ...",2180.0,"[{'token': 'Step', 'logprob': -0.011919195}, {...",Kim raises 320+430=<<320+430=750>>750 dollars....,2280,False,-25.034497,"{'Step 1:': -0.2270324247, 'Step 2:': -0.16740..."

In [16]:
combined_df = pd.concat([gsm_cor_sel, math_sel, gsm_incor], ignore_index=True)
combined_df.to_json("evaluation.jsonl", orient="records", lines=True)
combined_df

,question,reasoning_steps,model_answer,log_probabilities,gt_solution,correct_answer,is_correct,total_log_prob,stepwise_log_probs,category,level
0,"Farmer Brown has 20 animals on his farm, all e...",Step 1: Let the number of chickens be \( C \) ...,5.0,"[{'token': 'Step', 'logprob': -0.0633212800000...",Let C be the number of chickens.\nThere are 20...,5.0,True,-24.293495,"{'Step 1:': -0.1310692402, 'Step 2:': -0.11906...",NaN,NaN
1,Henry and 3 of his friends order 7 pizzas for ...,"Step 1: First, we need to calculate the total ...",14.0,"[{'token': 'Step', 'logprob': -0.0071874955}, ...",There are 7*8=<<7*8=56>>56 slices in total.\nT...,14.0,True,-13.433322,"{'Step 1:': -0.13620236460000001, 'Step 2:': -...",NaN,NaN
2,Each digit in the number 2001 is placed on a d...,Step 1: The number 2001 consists of the digits...,1.0,"[{'token': 'Step', 'logprob': -0.0401572734}, ...","There are four cards total, two of which have ...",0.0,False,-71.435032,"{'Step 1:': -0.0710904223, 'Step 2:': -0.17621...",counting_and_probability,2.0
3,The girls are trying to raise money for a carn...,"Step 1: First, we find out how much Alexandra ...",2180.0,"[{'token': 'Step', 'logprob': -0.011919195}, {...",Kim raises 320+430=<<320+430=750>>750 dollars....,2280.0,False,-25.034497,"{'Step 1:': -0.2270324247, 'Step 2:': -0.16740...",NaN,NaN

In [17]:
eval_df = pd.read_json("evaluation_with_choices.jsonl", lines=True)
eval_df

,question,reasoning_steps,model_answer,log_probabilities,gt_solution,correct_answer,is_correct,total_log_prob,stepwise_log_probs,category,level,Choices
0,"Farmer Brown has 20 animals on his farm, all e...",Step 1: Let the number of chickens be \( C \) ...,5,"[{'token': 'Step', 'logprob': -0.0633212800000...",Let C be the number of chickens.\nThere are 20...,5,True,-24.293495,"{'Step 1:': -0.1310692402, 'Step 2:': -0.11906...",None,NaN,"[4.0, 0.0, 5.0, 7.0]"
1,Henry and 3 of his friends order 7 pizzas for ...,"Step 1: First, we need to calculate the total ...",14,"[{'token': 'Step', 'logprob': -0.0071874955}, ...",There are 7*8=<<7*8=56>>56 slices in total.\nT...,14,True,-13.433322,"{'Step 1:': -0.13620236460000001, 'Step 2:': -...",None,NaN,"[16.0, 4.0, 14.0, 15.0]"
2,Each digit in the number 2001 is placed on a d...,Step 1: The number 2001 consists of the digits...,1,"[{'token': 'Step', 'logprob': -0.0401572734}, ...","There are four cards total, two of which have ...",0,False,-71.435032,"{'Step 1:': -0.0710904223, 'Step 2:': -0.17621...",counting_and_probability,2.0,"[1.0, 5.0, 2.0, 0.0]"
3,The girls are trying to raise money for a carn...,"Step 1: First, we find out how much Alexandra ...",2180,"[{'token': 'Step', 'logprob': -0.011919195}, {...",Kim raises 320+430=<<320+430=750>>750 dollars....,2280,False,-25.034497,"{'Step 1:': -0.2270324247, 'Step 2:': -0.16740...",None,NaN,"[2280.0, 2290.0, 2278.0, 2282.0]"

In [1]:
import pandas as pd

df = pd.read_json("question_bank_cleaned.jsonl", lines=True)

In [5]:
train_questions = df[df['dataset'] == 'train']

math_questions = df[(df['dataset'] == 'math') & (df['is_correct'] == False)].reset_index(drop=True)

math_questions = math_questions.iloc[[0, 3, 4, 5, 6, 10]].reset_index(drop=True)  
math_questions

,question,reasoning_steps,model_answer,log_probabilities,gt_solution,correct_answer,is_correct,total_log_prob,stepwise_log_probs,paragraph_reasoning,Analysis,Erroneous steps,dataset,question_id,category,level
0,A $4\times 4\times 4$ open cubical box contain...,Step 1: Consider the structure of the $4 \time...,64.0000,None,We count the complement. A cube that does not ...,52,False,-99.537313,"{'Step 1:': -0.3682932598, 'Step 2:': -0.33891...",Consider the structure of the $ 4 \times 4 \ti...,None,None,math,38.0,counting_and_probability,4.0
1,When a fair six-sided die is tossed on a table...,Step 1: A fair six-sided die has faces numbere...,0.8333,None,"If 6 is one of the visible faces, the product ...",1,False,-96.622040,"{'Step 1:': -0.2463127193, 'Step 2:': -0.17836...",A fair six-sided die has faces numbered 1 thro...,None,None,math,28.0,counting_and_probability,3.0
2,"A street has 50 houses on each side, for a tot...",Step 1: Determine the sequence of house number...,246.0000,None,If we combine the house numbers on the north a...,245,False,-70.004683,"{'Step 1:': -0.1912033286, 'Step 2:': -0.15656...",Determine the sequence of house numbers on the...,None,None,math,11.0,counting_and_probability,4.0
3,Kim has $10$ identical lamps and $3$ identical...,Step 1: We need to distribute 10 identical lam...,66.0000,None,Only the number of lamps on each table matters...,14,False,-30.274828,"{'Step 1:': -0.21624543840000002, 'Step 2:': -...",We need to distribute 10 identical lamps acros...,None,None,math,29.0,counting_and_probability,5.0
4,"How many numbers are in the list $$ 6,7,10,11,...",Step 1: Observe the pattern in the sequence: t...,46.0000,None,We first count the even terms of the sequence....,47,False,-57.239853,"{'Step 1:': -0.33314112220000003, 'Step 2:': -...",Observe the pattern in the sequence: the numbe...,None,None,math,10.0,counting_and_probability,3.0
5,How many numbers can be expressed as the sum o...,"Step 1: The set given is $\{0, 1, 2, 4, 8, 16\...",29.0000,None,"We see that the given numbers, expressed in bi...",31,False,-103.442798,"{'Step 1:': -0.1935318285, 'Step 2:': -0.28084...","The set given is $ \{0, 1, 2, 4, 8, 16\} $. We...",None,None,math,46.0,counting_and_probability,5.0

In [9]:
math = pd.read_json("MATH_test_questions_with_logprob.jsonl", lines=True)

math_correct = math[(math["is_correct"] == True) & (math["level"] >= 3.0) & (math["category"] == "counting_and_probability")]


sampled_math_correct = math_correct.sample(n=6, random_state=30)
sampled_math_correct["dataset"] = "math"

sampled_math_correct

,category,question,reasoning_steps,model_answer,level,log_probabilities,gt_solution,correct_answer,is_correct,total_log_prob,stepwise_log_probs,dataset
183,counting_and_probability,A palindrome is a number which reads the same ...,Step 1: A five-digit palindrome has the form A...,27.0,3,"[{'token': 'Step', 'logprob': -0.0241786838}, ...",A five-digit palindrome would be of the form $...,27.0,True,-32.593499,"{'Step 1:': -0.0501268242, 'Step 2:': -0.13897...",math
186,counting_and_probability,How many ways are there to answer a $10$-quest...,Step 1: Determine the total number of ways to ...,968.0,5,"[{'token': 'Step', 'logprob': -0.114513129}, {...",There are $2^{10} = 1024$ ways to answer the q...,968.0,True,-46.458029,"{'Step 1:': -0.1502956407, 'Step 2:': -0.14529...",math
98,counting_and_probability,How many ways are there to put 4 indistinguish...,Step 1: Since the balls are indistinguishable ...,5.0,3,"[{'token': 'Step', 'logprob': -0.0612951927}, ...","Since the balls are indistinguishable, the onl...",5.0,True,-32.769962,"{'Step 1:': -0.2778107694, 'Step 2:': -0.22312...",math
236,counting_and_probability,How many ways are there to divide 12 people in...,"Step 1: Since Henry must be in the group of 4,...",9240.0,4,"[{'token': 'Step', 'logprob': -0.0529133603000...","If Henry is in the group of 4, there are $\bin...",9240.0,True,-45.319104,"{'Step 1:': -0.2250450319, 'Step 2:': -0.20939...",math
49,counting_and_probability,License plates in the newly established state ...,Step 1: Determine the number of choices for th...,864000.0,3,"[{'token': 'Step', 'logprob': -0.0170423817}, ...","First, we can count the number of ways to arra...",864000.0,True,-36.006124,"{'Step 1:': -0.1158862588, 'Step 2:': -0.18709...",math
63,counting_and_probability,"Suppose that $*(n) = \left\{ n-2, n+2, 2n, \fr...",Step 1: We need to determine when the set \( *...,5.0,5,"[{'token': 'Step', 'logprob': -0.128207013}, {...","To have three distinct elements, two of $n-2$,...",5.0,True,-61.530091,"{'Step 1:': -0.1164749909, 'Step 2:': -0.24225...",math

In [ ]:


# -------------------------------
# Add training data at the top
final_df = pd.concat([train_questions, sampled_math_correct, math_questions], ignore_index=True)

final_df = final_df.drop(index=[1,3]).reset_index(drop=True)


final_df.to_json("question_bank_final.jsonl", orient="records", lines=True)

In [29]:
final_df = final_df.reset_index(drop=True)
final_df.to_json("question_bank_final.jsonl", orient="records", lines=True)
final_df

,question,reasoning_steps,model_answer,log_probabilities,gt_solution,correct_answer,is_correct,total_log_prob,stepwise_log_probs,paragraph_reasoning,Analysis,Erroneous steps,dataset,question_id,category,level
0,John picks 4 bananas on Wednesday. Then he pic...,"Step 1: On Wednesday, John picks 4 bananas. \n...",22.0,"[{'token': 'Step', 'logprob': -0.0073638256}, ...","Combining Wednesday and Thursday, John has 4 b...",22.0,True,-10.160249,"{'Step 1:': -0.0776833458, 'Step 2:': -0.09464...","On Wednesday, John picks 4 bananas. The next d...",None,None,train,NaN,None,NaN
1,Carlos is planting a lemon tree. The tree will...,"Step 1: First, we calculate the total income C...",12.0,None,He makes $10.5 selling lemons each year becaus...,13.0,False,-40.568187,"{'Step 1:': -0.2693612289, 'Step 2:': -0.21580...","First, we calculate the total income Carlos ea...",Erroneous steps: \nThe error occurs in the int...,Erroneous steps: \nThe error occurs in the int...,train,NaN,None,NaN
2,Ingrid drinks 8 cups of water every day. If t...,"Step 1: First, we need to calculate how many c...",15.0,"[{'token': 'Step', 'logprob': -0.0059571224000...",She drinks 8 cups of water a day so after 30 d...,15.0,True,-13.757998,"{'Step 1:': -0.17176034980000002, 'Step 2:': -...","First, we need to calculate how many cups of w...",None,None,train,NaN,None,NaN
3,When rolling a certain unfair six-sided die wi...,Step 1: Let's denote the probability of obtain...,17.0,None,"Let $p(a,b)$ denote the probability of obtaini...",29.0,False,-181.785633,"{'Step 1:': -0.2135267627, 'Step 2:': -0.15305...",Let's denote the probability of obtaining face...,Erroneous steps:\n \n**Step 18**: The error b...,Erroneous steps:\n \n**Step 18**: The error b...,train,NaN,None,NaN
4,"Mary has $6$ identical basil plants, and three...",Step 1: We need to distribute 6 identical basi...,28.0,"[{'token': 'Step', 'logprob': -0.0640836656}, ...","Since the plants are indistinguishable, we mus...",28.0,True,-21.536520,"{'Step 1:': -0.18283046930000002, 'Step 2:': -...",NaN,NaN,NaN,math,NaN,counting_and_probability,5.0
5,"Our basketball team has 10 players, including ...","Step 1: First, we need to determine the total ...",70.0,"[{'token': 'Step', 'logprob': -0.0238177758}, ...","If Steve and Danny are on opposite teams, ther...",70.0,True,-81.118338,"{'Step 1:': -0.26639105300000004, 'Step 2:': -...",NaN,NaN,NaN,math,NaN,counting_and_probability,5.0
6,There are 360 people in my school. 15 take ca...,Step 1: Let's define the sets:\n- Let \( C \) ...,110.0,"[{'token': 'Step', 'logprob': -0.5175089836}, ...",Let $x$ be the number of students taking physi...,110.0,True,-48.788060,"{'Step 1:': -0.1145902025, 'Step 2:': -0.11503...",NaN,NaN,NaN,math,NaN,counting_and_probability,5.0
7,Maria has three identical apples and three ide...,Step 1: Since Jacky cannot receive any oranges...,200.0,"[{'token': 'Step', 'logprob': -0.0662680566}, ...","First, just consider the apples. Imagine putti...",200.0,True,-36.810708,"{'Step 1:': -0.2822736963, 'Step 2:': -0.21503...",NaN,NaN,NaN,math,NaN,counting_and_probability,5.0
8,How many different bracelets have 3 identical ...,"Step 1: To solve this problem, we need to cons...",10.0,"[{'token': 'Step', 'logprob': -0.0815259144}, ...",Rotate each bracelet so the teal bead is at th...,10.0,True,-61.316677,"{'Step 1:': -0.38631394620000004, 'Step 2:': -...",NaN,NaN,NaN,math,NaN,counting_and_probability,5.0
9,"Given 5 colors to choose from, how many ways c...",Step 1: We need to determine the number of dis...,165.0,"[{'token': 'Step', 'logprob': -0.2363067418}, ...",We'll start with the naive estimate that there...,165.0,True,-69.349802,"{'Step 1:': -0.2953137978, 'Step 2:': -0.24693...",NaN,NaN,NaN,math,NaN,counting_and_probability,5.0
10,A $4\times 4\times 4$ open cubical box contain...,Step 1: Consider the structure of the $4 \time...,64.0,None,We count the complement. A cube that does not ...,52.0,False,-99.537313,"{'Step 1:': -0.3682932598, 'Step 2:': -0.33891...",Consider the structure of the $ 4 \times 4 \ti...,None,None,math,38.0,counting_and_probability,4.0
11,How many of the natural numbers from $1$ to $8...,Step 1: We need to find the number of natural ...,28.0,None,There are $10$ numbers with a $6$ in the hundr...,26.0,False,-71.215213,"{'Step 1:': -0.2251759852, 'Step 2:': -0.26338...",We need to find the number of natural numbers ...,None,None,math,57.0,counting_and_probability,4.0
12,"A street has 50 houses on each side, for a tot...",Step 1: Determine the sequence of house number...,246.0,None,If we combine the house numbers on the north a...,245.0,False,-70.004683,"{'Step 1:': -0.1912033286, 'Step 2:': -0.15656...",Determine the sequence of house numbers on the...,None,None,math,11.0,counting_and_probability,4.0
13,Kim has $10$ identical lamps and $3$ identical...,Step 1: We need to distribute 10 identical lam...,66.0,None,Only the number of lamps on each table matters...,14.0,False,-30.274828,"{'Step 1:': -0.21624543840000002, 'Step 2:': -...",We need to distribute 10 identical lamps acros...,None,None,math,29.0,counting_and_probability,5.0
14,The increasing list of five different integers...,Step 1: We need to find increasing lists of fi...,10.0,None,"After some trial and error, we obtain the two ...",2.0,False,-89.047330,"{'Step 1:': -0.14934915040000002, 'Step 2:': -...",We need to find increasing lists of five diffe...,None,None,math,8.0,counting_and_probability,4.0
15,How many numbers can be expressed as the sum o...,"Step 1: The set given is $\{0, 1, 2, 4, 8, 16\...",29.0,None,"We see that the given numbers, expressed in bi...",31.0,False,-103.442798,"{'Step 1:': -0.1935318285, 'Step 2:': -0.28084...","The set given is $ \{0, 1, 2, 4, 8, 16\} $. We...",None,None,math,46.0,counting_and_probability,5.0

In [ ]:
# Filter non-train questions
non_train = final_df[final_df['dataset'] != 'train'].reset_index(drop=True)

# Define desired truth pattern (15 total, with 3 incorrects)
pattern = [True, True, False, True, False, False, True, True, False, True, False, False] # 3 fix left random; 3 : 3, 4: 4, 5: 3

# Split based on correctness
correct = non_train[non_train['is_correct'] == True].copy()
incorrect = non_train[non_train['is_correct'] == False].copy()

# Check if we have enough
assert len(correct) >= pattern.count(True), "Not enough correct samples!"
assert len(incorrect) >= pattern.count(False), "Not enough incorrect samples!"

# Build reordered list
reordered = []
correct_index = 0
incorrect_index = 0

for is_corr in pattern:
    if is_corr:
        reordered.append(correct.iloc[correct_index])
        correct_index += 1
    else:
        reordered.append(incorrect.iloc[incorrect_index])
        incorrect_index += 1

# Create new DataFrame
non_train_reordered = pd.DataFrame(reordered).reset_index(drop=True)

# Combine with training questions at the top
train_questions = final_df[final_df['dataset'] == 'train']
final_reordered_df = pd.concat([train_questions, non_train_reordered], ignore_index=True)
final_reordered_df

,question,reasoning_steps,model_answer,log_probabilities,gt_solution,correct_answer,is_correct,total_log_prob,stepwise_log_probs,paragraph_reasoning,Analysis,Erroneous steps,dataset,question_id,category,level
0,John picks 4 bananas on Wednesday. Then he pic...,"Step 1: On Wednesday, John picks 4 bananas. \n...",22.0,"[{'token': 'Step', 'logprob': -0.0073638256}, ...","Combining Wednesday and Thursday, John has 4 b...",22.0,True,-10.160249,"{'Step 1:': -0.0776833458, 'Step 2:': -0.09464...","On Wednesday, John picks 4 bananas. The next d...",None,None,train,NaN,None,NaN
1,Carlos is planting a lemon tree. The tree will...,"Step 1: First, we calculate the total income C...",12.0,None,He makes $10.5 selling lemons each year becaus...,13.0,False,-40.568187,"{'Step 1:': -0.2693612289, 'Step 2:': -0.21580...","First, we calculate the total income Carlos ea...",Erroneous steps: \nThe error occurs in the int...,Erroneous steps: \nThe error occurs in the int...,train,NaN,None,NaN
2,Ingrid drinks 8 cups of water every day. If t...,"Step 1: First, we need to calculate how many c...",15.0,"[{'token': 'Step', 'logprob': -0.0059571224000...",She drinks 8 cups of water a day so after 30 d...,15.0,True,-13.757998,"{'Step 1:': -0.17176034980000002, 'Step 2:': -...","First, we need to calculate how many cups of w...",None,None,train,NaN,None,NaN
3,When rolling a certain unfair six-sided die wi...,Step 1: Let's denote the probability of obtain...,17.0,None,"Let $p(a,b)$ denote the probability of obtaini...",29.0,False,-181.785633,"{'Step 1:': -0.2135267627, 'Step 2:': -0.15305...",Let's denote the probability of obtaining face...,Erroneous steps:\n \n**Step 18**: The error b...,Erroneous steps:\n \n**Step 18**: The error b...,train,NaN,None,NaN
4,"Mary has $6$ identical basil plants, and three...",Step 1: We need to distribute 6 identical basi...,28.0,"[{'token': 'Step', 'logprob': -0.0640836656}, ...","Since the plants are indistinguishable, we mus...",28.0,True,-21.536520,"{'Step 1:': -0.18283046930000002, 'Step 2:': -...",NaN,NaN,NaN,math,NaN,counting_and_probability,5.0
5,"Our basketball team has 10 players, including ...","Step 1: First, we need to determine the total ...",70.0,"[{'token': 'Step', 'logprob': -0.0238177758}, ...","If Steve and Danny are on opposite teams, ther...",70.0,True,-81.118338,"{'Step 1:': -0.26639105300000004, 'Step 2:': -...",NaN,NaN,NaN,math,NaN,counting_and_probability,5.0
6,A $4\times 4\times 4$ open cubical box contain...,Step 1: Consider the structure of the $4 \time...,64.0,None,We count the complement. A cube that does not ...,52.0,False,-99.537313,"{'Step 1:': -0.3682932598, 'Step 2:': -0.33891...",Consider the structure of the $ 4 \times 4 \ti...,NaN,NaN,math,38.0,counting_and_probability,4.0
7,There are 360 people in my school. 15 take ca...,Step 1: Let's define the sets:\n- Let \( C \) ...,110.0,"[{'token': 'Step', 'logprob': -0.5175089836}, ...",Let $x$ be the number of students taking physi...,110.0,True,-48.788060,"{'Step 1:': -0.1145902025, 'Step 2:': -0.11503...",NaN,NaN,NaN,math,NaN,counting_and_probability,5.0
8,How many of the natural numbers from $1$ to $8...,Step 1: We need to find the number of natural ...,28.0,None,There are $10$ numbers with a $6$ in the hundr...,26.0,False,-71.215213,"{'Step 1:': -0.2251759852, 'Step 2:': -0.26338...",We need to find the number of natural numbers ...,NaN,NaN,math,57.0,counting_and_probability,4.0
9,"A street has 50 houses on each side, for a tot...",Step 1: Determine the sequence of house number...,246.0,None,If we combine the house numbers on the north a...,245.0,False,-70.004683,"{'Step 1:': -0.1912033286, 'Step 2:': -0.15656...",Determine the sequence of house numbers on the...,NaN,NaN,math,11.0,counting_and_probability,4.0
10,Maria has three identical apples and three ide...,Step 1: Since Jacky cannot receive any oranges...,200.0,"[{'token': 'Step', 'logprob': -0.0662680566}, ...","First, just consider the apples. Imagine putti...",200.0,True,-36.810708,"{'Step 1:': -0.2822736963, 'Step 2:': -0.21503...",NaN,NaN,NaN,math,NaN,counting_and_probability,5.0
11,How many different bracelets have 3 identical ...,"Step 1: To solve this problem, we need to cons...",10.0,"[{'token': 'Step', 'logprob': -0.0815259144}, ...",Rotate each bracelet so the teal bead is at th...,10.0,True,-61.316677,"{'Step 1:': -0.38631394620000004, 'Step 2:': -...",NaN,NaN,NaN,math,NaN,counting_and_probability,5.0
12,Kim has $10$ identical lamps and $3$ identical...,Step 1: We need to distribute 10 identical lam...,66.0,None,Only the number of lamps on each table matters...,14.0,False,-30.274828,"{'Step 1:': -0.21624543840000002, 'Step 2:': -...",We need to distribute 10 identical lamps acros...,NaN,NaN,math,29.0,counting_and_probability,5.0
13,"Given 5 colors to choose from, how many ways c...",Step 1: We need to determine the number of dis...,165.0,"[{'token': 'Step', 'logprob': -0.2363067418}, ...",We'll start with the naive estimate that there...,165.0,True,-69.349802,"{'Step 1:': -0.2953137978, 'Step 2:': -0.24693...",NaN,NaN,NaN,math,NaN,counting_and_probability,5.0
14,The increasing list of five different integers...,Step 1: We need to find increasing lists of fi...,10.0,None,"After some trial and error, we obtain the two ...",2.0,False,-89.047330,"{'Step 1:': -0.14934915040000002, 'Step 2:': -...",We need to find increasing lists of five diffe...,NaN,NaN,math,8.0,counting_and_probability,4.0
15,How many numbers can be expressed as the sum o...,"Step 1: The set given is $\{0, 1, 2, 4, 8, 16\...",29.0,None,"We see that the given numbers, expressed in bi...",31.0,False,-103.442798,"{'Step 1:': -0.1935318285, 'Step 2:': -0.28084...","The set given is $ \{0, 1, 2, 4, 8, 16\} $. We...",NaN,NaN,math,46.0,counting_and_probability,5.0

In [32]:
final_reordered_df.to_json("question_bank_final.jsonl", orient="records", lines=True)